name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  cicd:
    name: cicd
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: get version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: clean install dependencies
        run: npm ci

      - name: compile and create vsix
        run: npm run compile

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: ${{ github.workspace }}/*.vsix

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.workspace }}/vsix-viewer-${{steps.package-version.outputs.current-version}}.vsix
